name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 12 * * 1" # Every Monday at noon

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FAKE_API_KEY: ${{ secrets.FAKE_API_KEY }}
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests and save output
        run: |
          npm test | tee test-report.txt

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-report.txt

      - name: Print fake API key (for demo only — do not log real secrets)
        run: echo "Using FAKE_API_KEY=$FAKE_API_KEY"

      - name: Trigger Render Deploy Webhook
        run: curl -X POST $RENDER_DEPLOY_HOOK
